{% set version = "1.5" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-estimability
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/estimability_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/estimability/estimability_{{ version }}.tar.gz
  sha256: b32c5f6157cbeaf96e42be3d4d33637de542debbc6dd2a9a19814980ed46dc68

build:
  number: 1
  skip: true  # [r_base == "4.2" or win]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('estimability')"           # [not win]
    - "\"%R%\" -e \"library('estimability')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=estimability
  license: GPL-3.0-or-later
  summary: Provides tools for determining estimability of linear functions  of regression coefficients, and 'epredict' methods that handle  non-estimable cases correctly. Estimability theory is discussed in many linear-models textbooks including Chapter 3 of Monahan, JF (2008),  "A Primer on Linear Models", Chapman and Hall
    (ISBN 978-1-4200-6201-4).
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
